#ifndef CONSTANTS_H
#define CONSTANTS_H

#define QSETTINGS_MOVIE_COLLECTIONS_ARRAY_NAME	"movie_collections"
#define QSETTINGS_MOVIE_COLLECTIONS_COLLECTION_NAME "collectionName"
#define QSETTINGS_MOVIE_COLLECTIONS_COLLECTION_FILENAME "collectionFileName"


#define XML_MOVIE_COLLECTION_TOP_ELEMENT	"movies"
#define XML_MOVIE_COLLECTION_MOVIE_ELEMENT	"movie"
#define XML_MOVIE_COLLECTION_MOVIE_NAME		"name"
#define XML_MOVIE_COLLECTION_MOVIE_YEAR		"year"
#define XML_MOVIE_COLLECTION_MOVIE_RATING	"rating"
#define XML_MOVIE_COLLECTION_MOVIE_TAG		"tag"
#define XML_MOVIE_COLLECTION_MOVIE_GENRE	"genre"
#define XML_MOVIE_COLLECTION_MOVIE_IMDB		"imdblink"
#define XML_MOVIE_COLLECTION_MOVIE_LASTWATCHED "lastwatched"

#endif // CONSTANTS_H
